"""
Beat Plan endpoint — Agent 6: Beat Intelligence & Coverage.
"""
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import List, Optional
from datetime import date, datetime

from app.core.security import get_current_user, TokenData

router = APIRouter()


class OutletStop(BaseModel):
    outlet_id: str
    outlet_name: str
    address: str
    priority: int           # 1=highest
    trust_score: float
    last_visited: Optional[date] = None
    outstanding_amount: float = 0.0
    priority_skus: List[str] = []
    notes: Optional[str] = None


class BeatPlan(BaseModel):
    beat_plan_id: str
    salesman_id: str
    date: date
    route_name: str
    total_stops: int
    stops: List[OutletStop]
    estimated_revenue_opportunity: float
    ghost_risk_outlets: List[str]  # outlet IDs


@router.get("/{salesman_id}", response_model=BeatPlan, summary="Get daily beat plan for a salesman")
async def get_beat_plan(
    salesman_id: str,
    plan_date: Optional[date] = None,
    user: TokenData = Depends(get_current_user),
):
    """
    Returns today's optimised beat plan for the given salesman.
    Generated by Agent 6 using shortest-path routing + outlet priority scoring.
    """
    target_date = plan_date or date.today()
    # TODO: fetch from Agent 6 generated plans or compute on-demand
    return BeatPlan(
        beat_plan_id=f"BP-{salesman_id}-{target_date}",
        salesman_id=salesman_id,
        date=target_date,
        route_name="Route A — Patna Central",
        total_stops=25,
        stops=[],
        estimated_revenue_opportunity=125000.0,
        ghost_risk_outlets=[],
    )


@router.get("/coverage/gaps", summary="Get coverage gap report")
async def get_coverage_gaps(
    days: int = 7,
    user: TokenData = Depends(get_current_user),
):
    """
    Outlets not visited in the past N days — coverage gap report.
    """
    # TODO: query outlet visit logs + beat logs
    return {"gaps": [], "period_days": days, "total_missed_outlets": 0}


@router.get("/ghost-visits/report", summary="Ghost visit detection report")
async def ghost_visit_report(
    salesman_id: Optional[str] = None,
    user: TokenData = Depends(get_current_user),
):
    """
    Salesmen who logged check-ins with zero orders and zero 2-way messages.
    """
    # TODO: compute from Agent 6 ghost visit logic
    return {"ghost_visits": [], "estimated_missed_revenue": 0.0}


@router.post("/generate", summary="Generate beat plans for all salesmen (Agent 6)")
async def generate_beat_plans(user: TokenData = Depends(get_current_user)):
    """Trigger Agent 6 to generate tomorrow's beat plans for all salesmen in tenant."""
    # TODO: enqueue Agent 6 pipeline job
    return {"queued": True, "tenant_id": user.tenant_id}


@router.post("/checkin", summary="Salesman logs a check-in at an outlet")
async def log_checkin(
    salesman_id: str,
    outlet_id: str,
    gps_lat: Optional[float] = None,
    gps_lon: Optional[float] = None,
    user: TokenData = Depends(get_current_user),
):
    """
    Records a salesman check-in. GPS coordinates optionally provided.
    Cross-referenced with 2-way chat and orders to detect ghost visits.
    """
    # TODO: persist to beat_checkins table, trigger ghost-visit logic
    return {
        "checkin_id": f"CHK-{salesman_id}-{datetime.utcnow().timestamp()}",
        "outlet_id": outlet_id,
        "verified": False,   # becomes True once chat/order correlation confirmed
    }
