"""
Risk Alerts endpoint (Agent 3 output surface).
"""
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from enum import Enum

from app.core.security import get_current_user, TokenData

router = APIRouter()


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertType(str, Enum):
    CREDIT_RISK = "CREDIT_RISK"
    SCHEME_LEAKAGE = "SCHEME_LEAKAGE"
    RETURN_SUSPICIOUS = "RETURN_SUSPICIOUS"
    EXPIRY_WARNING = "EXPIRY_WARNING"
    GST_COMPLIANCE = "GST_COMPLIANCE"
    GHOST_VISIT = "GHOST_VISIT"
    PAYMENT_DUE = "PAYMENT_DUE"
    QUICK_COMMERCE = "QUICK_COMMERCE"


class RiskAlert(BaseModel):
    alert_id: str
    alert_type: AlertType
    severity: AlertSeverity
    title: str
    description: str
    affected_entity_id: str
    affected_entity_type: str   # retailer | salesman | sku | route
    rupee_impact: Optional[float] = None
    recommended_action: Optional[str] = None
    created_at: datetime
    acknowledged: bool = False


@router.get("/", summary="List all active risk alerts for tenant")
async def list_alerts(
    severity: Optional[AlertSeverity] = None,
    alert_type: Optional[AlertType] = None,
    limit: int = 50,
    offset: int = 0,
    user: TokenData = Depends(get_current_user),
):
    """
    Returns all unacknowledged risk alerts for the distributor's tenant.
    Alerts are generated by Agent 3 (Risk, Scheme & Compliance Intelligence).
    """
    # TODO: query alerts table filtered by tenant_id, severity, type
    return {"alerts": [], "total": 0}


@router.get("/{alert_id}", response_model=RiskAlert, summary="Get alert detail")
async def get_alert(alert_id: str, user: TokenData = Depends(get_current_user)):
    """Fetch detailed view of a single alert including recommended action card."""
    # TODO: fetch from DB
    return RiskAlert(
        alert_id=alert_id,
        alert_type=AlertType.CREDIT_RISK,
        severity=AlertSeverity.WARNING,
        title="High credit outstanding — Mahesh Stores",
        description="₹48,000 outstanding for 45+ days. Score dropped to Tier C.",
        affected_entity_id="RET-001",
        affected_entity_type="retailer",
        rupee_impact=48000.0,
        recommended_action="Send collection nudge via Telegram. Consider reducing credit limit.",
        created_at=datetime.utcnow(),
    )


@router.patch("/{alert_id}/acknowledge", summary="Acknowledge an alert")
async def acknowledge_alert(alert_id: str, user: TokenData = Depends(get_current_user)):
    """Mark alert as reviewed / acknowledged by distributor."""
    # TODO: update acknowledged=True in DB
    return {"alert_id": alert_id, "acknowledged": True}


@router.post("/run-scan", summary="Trigger a full risk scan (Agent 3)")
async def run_risk_scan(user: TokenData = Depends(get_current_user)):
    """
    Manually trigger Agent 3 to scan entire tenant ledger for new risks.
    In production this runs on a schedule.
    """
    # TODO: enqueue Agent 3 run for tenant_id
    return {"queued": True, "tenant_id": user.tenant_id}
